#
# This file contains configuration flags to customize your site
#

url: https://hardadwij.github.io
theme_color: '#fff'

keywords: hrd, human, resource, development, personalia, karir, recruiter, sdm

name: Hardani Dwi Jayanti
position: Human Resource Specialist
description: I am majoring in Psychology and I am interested in Industrial & Organizational. I am used to recruiting employees, payroll, people & development, GA Administration, HR Administration, BPJS, psychology test, training, counseling process, HRIS Talenta, etc.
location: 
phone: +62 878 3861 0808
email: hardadwij@gmail.com
blog: https://hardadj.blogspot.com/
linkedin: https://www.linkedin.com/in/hardadwij/
avatar: assets/img/avatar.jpeg

education:
  - title: Mercu Buana University
    bachelor: Master of Psychology
    location: Yogyakarta
    gpa: 
    year: 2021-2023
    icon: assets/img/education/umby.jpeg
  - title: Ahmad Dahlan University
    bachelor: Bachelor of Psychology
    location: Yogyakarta
    gpa: 
    year: 2014-2018
    icon: assets/img/education/uad.jpeg

expertise:

experience:
  - title: Skill Academy by Ruangguru
    description: 
      - point: Help open and close webinar events
      - point: Help display the material needed by the instructor
      - point: Direct and manage webinar attendees
      - point: Assess the results of the participants' assignments
    position: Instructor Assistant
    status: Contract
    work: Remote
    duration: 
    year: May 2023 - Now
    icon: assets/img/corporate/skill-academy.jpeg
  - title: Cybers Global Indonesia
    description: 
      - point: Recruitment end to end
      - point: Public Relation with mitra
      - point: Administration
      - point: Psychological test
      - point: Analyze the workload
    position: Human Resources Generalist
    status: Freelance
    work: Remote
    duration: 
    year: Sep 2022 - Jan 2023
    icon: assets/img/corporate/cgi.jpeg
  - title: Asta Bumi Cipta
    description:
      - point: Recruitment and selection
      - point: Presents psychological test, scoring, interpretation
      - point: Employee employment contracts
      - point: BPJS and Jamsostek management
      - point: Filling employee database
      - point: Payroll
      - point: Employee attendance recap
      - point: Employee development
      - point: Create Job Descriptions and SOP
      - point: Legal (WLKP, NPWP BU)
    position: Human Resources Generalist
    status: Full Time
    duration: 
    year: Aug 2021 - Apr 2022
    icon: assets/img/corporate/asta.jpeg
  - title: JogjaCamp
    description:
      - point: Recruitment and selection
      - point: Presents psychological test, scoring, interpretation
      - point: Employee employment contracts (PKWT)
      - point: BPJS and Jamsostek management
      - point: Licensing arrangements at the employment agency
      - point: Filling employee database
      - point: Payroll
      - point: Employee attendance recap
      - point: Employee development
      - point: Create Job Descriptions and SOP
      - point: Administration of official visits
      - point: Legal (ISO 27001, WLKP)
      - point: Inventaris (GA)
    position: Human Resources Management
    status: Full Time
    duration: 
    year: Jan 2020 - Apr 2021
    icon: assets/img/corporate/jc.jpeg
  - title: Syncore
    description:
      - point: Creating job vacancies, screening candidates, calling candidates, tests, interviews, employee induction, employment contracts
      - point: Administration
      - point: Event Organizer
      - point: employee development
      - point: Evaluate employee performance
      - point: Inventaris
      - point: Recap the employee's present data and analyze the workload
    position: Human Resources Specialist
    status: Full Time
    duration: 
    year: Jan 2019 - Dec 2019
    icon: assets/img/corporate/syncore.jpeg
  - title: Archira Consultans
    description:
      - point: Manage BPJS
      - point: Administration
      - point: Make SOP
      - point: Creating job vacancies, screening candidates, calling candidates, tests, interviews.
    position: SDM & Operasional
    status: Internship
    duration: 
    year: Jan 2019
    icon: assets/img/corporate/archira.jpeg


#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed, or unminify using :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
